### ISSUE TITLE
Read snmp from other device

### ISSUE THREAD

**Issue by Gastondamian** [rexpark/Arduino-SNMP#4]
I want to read snmp from UPS and turn on  a led in arduino, Is there any library to read snmp?

**Comment by rexpark** [comment]
Theoretically this library can do it. You'd need to set your UPS to send traps to the Arduino's IP address. Then configure your SNMPAgent class to look for SNMP_PDU_TRAP or SNMP_PDU_TRAP2 PDU types.

If you look in the example project and open the SNMPAgent.cpp file you can see how it's looking for SNMP_PDU_GET and SNMP_PDU_SET types in the SNMPAgent::process_snmp_pdu() method. You'd change that to look for the trap types and then write your own processing logic for deciphering the data like in SNMPAgent::process_config_command().
